language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
script: nikola build
after_success: 
    # Get to the Travis build directory, configure git and clone the repo
    - cd $HOME
    - git config --global user.email ${GH_EMAIL}
    - git config --global user.name ${GH_NAME}
    # Commit and Push the Changes
    - git clone --quiet --branch=gh-pages https://${GH_TOKEN}@github.com/johnfoster-pge-utexas/PGE383-AdvGeomechanics gh-pages > /dev/null
    - cd gh-pages
    - cp -Rf $HOME/build/johnfoster-pge-utexas/PGE383-AdvGeomechanics/output/* .
    - git add -A
    - git commit -m "Travis CI autocommit from travis build $TRAVIS_BUILD_NUMBER"
    - git push -fq origin gh-pages > /dev/null
    - git push -fq https://${GH_TOKEN}@github.com/johntfoster/PGE383-AdvGeomechanics gh-pages
